import { DefectCardData } from "./DefectCard";

export function Report({ card }: { card: DefectCardData }) {
  return (
    <div
      id="report"
      className="p-8 bg-white text-black max-w-4xl mx-auto"
      style={{ pageBreakAfter: "always" }}
    >
      <div className="mb-8">
        <h1 className="text-4xl font-bold mb-2">Inspection Report</h1>
        <p className="text-sm text-gray-600">
          Generated: {new Date().toLocaleString()}
        </p>
      </div>

      <hr className="my-6" />

      <div className="mb-8">
        <h2 className="text-2xl font-bold mb-4">Defect Summary</h2>
        <div className="bg-gray-50 p-4 rounded border border-gray-200">
          <p className="text-lg">
            <span className="font-bold">Defect Type:</span>{" "}
            {card.defect.replace(/_/g, " ").toUpperCase()}
          </p>
          <p className="text-lg mt-2">
            <span className="font-bold">Confidence:</span>{" "}
            {(card.confidence * 100).toFixed(1)}%
          </p>
          <p className={`text-xl font-bold mt-4 ${
            card.pass_fail === "fail" ? "text-red-600" : "text-green-600"
          }`}>
            Status: {card.pass_fail === "fail" ? "FAIL" : "PASS"}
          </p>
        </div>
      </div>

      <hr className="my-6" />

      <div className="mb-8">
        <h2 className="text-2xl font-bold mb-4">Quality Standard</h2>
        <div className="bg-blue-50 border-l-4 border-blue-500 p-4 rounded-r">
          <p className="text-sm font-bold text-blue-700 uppercase tracking-wide">
            {card.cited_standard.source}
          </p>
          <p className="text-sm font-semibold text-blue-600 mt-1">
            Clause: {card.cited_standard.clause_id}
          </p>
          <p className="text-base italic text-gray-800 mt-3 leading-relaxed">
            &ldquo;{card.cited_standard.text}&rdquo;
          </p>
        </div>
      </div>

      <hr className="my-6" />

      <div className="mb-8">
        <h2 className="text-2xl font-bold mb-4">Root Cause Analysis</h2>
        <p className="text-base leading-relaxed text-gray-800">
          {card.root_cause}
        </p>
      </div>

      <hr className="my-6" />

      <div className="mb-8">
        <h2 className="text-2xl font-bold mb-4">Recommended Action</h2>
        <p className="text-base leading-relaxed text-gray-800">
          {card.recommended_action}
        </p>
      </div>

      <hr className="my-6" />

      <div className="text-sm text-gray-500 mt-8 pt-4 border-t border-gray-200">
        <p>This report was generated by InspectAI, an automated garment QA system.</p>
        <p>For questions or appeals, contact your QA supervisor.</p>
      </div>
    </div>
  );
}
